language: python
python:
- "2.7"
- "3.4"
- "3.5"
- "3.6"
- "3.7"
- "3.8"

install:
 - pip install --upgrade pip
 - pip install poetry
 - poetry install

script:
 - poetry run python pyhtmlcv.py

# Deploy to GitHub pages
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: generated/cv.json/
  github-token: $GITHUB_TOKEN
  target-branch: gh-pages
  repo: lietu/pyhtmlcv
  on:
    branch: master
    python: 3.6
